# Site
name: 'Sneha Kataria'
description: 'SK blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
email: 'snehakataria1244@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  Sneha:
    name:           Sneha Kataria
    site:           https://sneha-kataria.github.io/blog/
    avatar:         /assets/images/avatar2.jpg
    bio:            "Senior Product Manager"
    email:          snehakataria1244@gmail.com
    linkedin:       https://www.linkedin.com/in/snehakataria/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Sneha Kataria
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]