title: Sneha Kataria
permalink: /:title.html
#theme: minima
remote_theme: mmistakes/minimal-mistakes

google_analytics: G-K52C9QRRNY

description: >-
  Sneha Kataria's Blog

#url: "https://domain.com/"

header_pages:
  - all-posts.html
  - product-management.html
  - analysis.html

license: "CC BY-NC-ND 4.0"
license_url: "creativecommons.org/licenses/by-nc-nd/4.0/"

linkedin_username: snehakataria
github_username: sneha-kataria
email: snehakataria1244@gmail.com

show_excerpts: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache